### ISSUE TITLE
Remove Django requirement from openbadges_bakery

### ISSUE THREAD

**Issue by ottonomy** [openbadges/badgecheck#15]
Python package openbadges_bakery is a dependency of badgecheck - Replace usage of Django's File class with underlying python class and post a new version before reincluding it in badgecheck.

**Comment by ottonomy** [comment]
https://github.com/concentricsky/openbadges-bakery This package, at tag 1.0.0b0+ is now updated to remove this requirement. Looking for comments on the python API before we integrate it into this project. 

It expects an open file. Is that weird?
```python
from openbadges_bakery import unbake

with open('filename.png', 'r') as f:
    data = unbake(f)
```

**Comment by ottonomy** [comment]
@mgylling and @ViktorHaag Comments welcome. When we get to a sprint or two from now, we'll be allowing files as an input format for the CLI and python interfaces.

**Comment by ViktorHaag** [comment]
digression: @mgylling Have the licensing implications of this dependency been considered? I'm not sure what the disposition is between IMS and the openbadges initiative -- i.e. is the openbadges badgecheck project going to take place "within the IMS unmbrella"?

I know that I can contribute work (a) to Apache-licensed projects, and (b) to projects within the IMS umbrella, but the bakery's license is different and not sure how that affects the general licensing situation here. (For example -- if this project uses the bakery project, is it subject to free and open distribution of its source?)

**Comment by ViktorHaag** [comment]
On the matter at hand -- Python's compression utils in the stdlib seems to use a pattern something like this:

```
from openbadges_bakery import bakery

with bakery.open('/my/file/foo.png', 'rb') as f:
   unbaked_content = f.read()

content = 'badge content'
with bakery.open('/my/file/foo.png', 'wb') as f:
    f.write(content)

Does that make more sense than what the bakery does now (where it expects file handles)?
```

**Comment by mgylling** [comment]
@ViktorHaag, licensing etc: yes, this project will be done under the IMS umbrella, and under Apache. (We will be moving the entire OB github organization into the IMS organization any time now btw.) As for the bakery dependency, yes this might be an issue. I will discuss with @ottonomy and see what solution we can find to keep things clean and tidy licensewise. Stay tuned.

**Comment by ViktorHaag** [comment]
Thanks, @mgylling, and thanks for your understanding. 8/

**Comment by ottonomy** [comment]
I will relicense as Apache2 pending approval from CSky leadership.

**Comment by ViktorHaag** [comment]
That would be cool; thanks so much, @ottonomy.

**Comment by ottonomy** [comment]
Relicensed as Apache2. See: https://github.com/concentricsky/openbadges-bakery
