### ISSUE TITLE
Queue up tasks based on input type for URL input

### ISSUE THREAD

**Issue by ottonomy** [openbadges/badgecheck#22]
After storing input and analyzing it to determine type, tasks must be queued up to process the type. 

URI-type input:

- [x] Fetch result
- [x] Store fetched document body
- [x] Compact into latest context
- [x] Assign IRI if not exists (trigger refetch/overwrite from IRI if different from input)
- [x] Flatten graph; store and label nodes
- [x] Detect input object class from `@type` declaration
- [x] Add required property presence checks for discovered class
- [x] Add property value datatype checks for fields of [primitive datatypes](https://openbadgespec.org/#primitive-datatypes)
- [x] Add property value checks for `@id`-type fields: either URI or blank node identifier for local node
- [x] Add fetch task for relevant & necessary URI-type ids.
- [x] Add process task for expected class
- [ ] Add hosted assertion verification URI check task
- [ ] Resolve differences between fetched and hosted node, store in messages

**Comment by mgylling** [comment]
Done in #42.
