### ISSUE TITLE
Task: Fetch URL

### ISSUE THREAD

**Issue by ottonomy** [openbadges/badgecheck#24]
Fetch a URL and store in graph.

Queued up like this:
```py
store.dispatch(fetch_url("http://example.com"))
```

Creates action like this:
```py
{
    'type': CREATE_ACTION,
   'name': FETCH_URL_ACTION,
    'url': 'http://example.com'
}
```

Which is processed by the fetch url task function and triggers a STORE_GRAPH_NODE action.

**Comment by mgylling** [comment]
Done in #28.
