### ISSUE TITLE
STORE_NODE reducer function

### ISSUE THREAD

**Issue by ottonomy** [openbadges/badgecheck#30]
The `STORE_NODE` reducer function should 
* Ensure the `id` field is populated
* Assign blank node `id`s if necessary.
* Flatten results (any `{}`-type embedded nodes should be stored separately and linked via their ID or a blank node identifier.
* blank node identifier assignment should be deterministic.

Also: evaluate factors that would make it necessary for this to be a task, like if it needs to emit additional actions/add new tasks.

**Comment by mgylling** [comment]
Done in #37.
