### ISSUE TITLE
Document loader with prefetched result support

### ISSUE THREAD

**Issue by ottonomy** [openbadges/badgecheck#31]
The pyld package allows passing in of a document loader function to replace its [default](https://github.com/digitalbazaar/pyld/blob/master/lib/pyld/jsonld.py#L365) (and simple) one. 

We should:
* Build a loader based on the requests package
* Intercept requests for known high-volume static content and provide them from within the app
* Be possible to upgrade to use with a cache. For example: https://pypi.python.org/pypi/requests-cache
* Return the dict format the pyld package expects.

```py
{
    'contextUrl': None,
    'documentUrl': url,
    'document': response.text
}
```

**Comment by ViktorHaag** [comment]
I have a branch with this work done, but it depends on PR #35 ; I'll submit the PR after that first PR gets merged to keep things simpler.

**Comment by mgylling** [comment]
Done in #36.
