### ISSUE TITLE
Add DateTime Validator

### ISSUE THREAD

**Issue by ottonomy** [openbadges/badgecheck#43]
```py
tasks.validation.PrimitiveValueValidator(tasks.validation.ValueTypes.DATETIME)("2016-03-31T00:00Z")
```

* Should enforce 2.0 rules in the Open Badges Specification (must include timestamp and timezone indicator)

**Comment by ViktorHaag** [comment]
As I understand the requirements, this means that the DT value must be:

- capably parseable as an ISO8601 datetime
- must have trailing timezone info that's in one of these forms: <time>Z, <time>+/-hh:mm, <time>+/-hhmm, or <time>+/-hh.

I will proceed on that assumption.

**Comment by ViktorHaag** [comment]
One further wrinkle (from wikipedia's explanation of ISO8601):

> ISO 8601 permits the hyphen (-) to be used as the minus (−) character when the character set is limited.[19] In contrast, RFC 3339 explicitly requires the hyphen (-) symbol to represent negative offsets and does not allow for use of the minus (−) symbol.[20]

**Comment by ViktorHaag** [comment]
I assume that we have to cope with either the hyphen or minus character being used, since the Open Badges spec says "ISO8601"...

**Comment by ViktorHaag** [comment]
Things will be a lot easier if we say in the spec: if there's no tzinfo specified in the date-time, the assumed timezone is Z (i.e. UTC). I believe that's what ISO8601 actually says... are we cool with that? Is that worthy of checking on a call?

**Comment by ottonomy** [comment]
@ViktorHaag interesting suggestion. How much easier? We don't wish to make any changes to the spec as part of implementing this validator if we can avoid it. Not that your suggested change is unreasonable...

**Comment by ViktorHaag** [comment]
Well, there's two orders of easier:

1 - if we assume that "no tzinfo is the same as UTC", then we can probably get away with just saying "does this datetime string parse as a datetime by aniso8601, and can I get the tzinfo value I expect out of the datetime that it retrieves"? This lets us avoid a fair amount of finicky tzinfo validity checking (my PR does _some_ validity checking, but really leans on aniso8601 to say what a valid _value_ a tzinfo string might have: the PR regex only checks for digits and length).

2 - If we can discount having to check for minus signs (which aniso8601 doesn't seem to support at all, anyway), then that makes things easier by not having to mess with non-ascii characters in the input or test strings... (I kind of punted on this last point in my PR)

**Comment by ottonomy** [comment]
👍 this does seem a reasonable first cut.

**Comment by mgylling** [comment]
Done in #57.
