### ISSUE TITLE
Messages Reducer

### ISSUE THREAD

**Issue by ottonomy** [openbadges/badgecheck#8]
The Messages Reducer manages errors and other informational messages generated in verification & validation tasks.
* `NEW_MESSAGE` action would be a fine one to start with.

**Comment by ViktorHaag** [comment]
Does this mean you'd like to "log" these messages in the state object itself as new fields? (i.e. a list that's a transcript of all such messages?)

**Comment by ottonomy** [comment]
Things that are interesting to report:
* Sort errors by type
* Quickly find what node has a problem

**Comment by ottonomy** [comment]
I've implemented this as a `REPORT_MESSAGE` type action in the graphs package. This is on the `feature/recipient-profile` branch to be merged by PR 112

**Comment by ottonomy** [comment]
Merged.
