### ISSUE TITLE
Python API Response

### ISSUE THREAD

**Issue by ottonomy** [openbadges/badgecheck#84]
API response should include:
```json
{
  "graph": [{}],
  "errorCount": 0,
  "warningCount": 0,
  "messages": [{}]
}
```

**Comment by ViktorHaag** [comment]
Hey @ottonomy -- do the messages self-identify as errors or warnings? That might be useful so that a receiving process could filter out messages that "were only warnings" for varying levels of verbosity?

**Comment by ottonomy** [comment]
@ViktorHaag Yes. Each message will contain a `messageLevel` property with a value that is one of `ERROR`, `WARNING`, or `INFO`. Right now, all failing tasks in the app so far return the ERROR level. Any task you queue up with the property "messageLevel": MESSAGE_LEVEL_WARNING will count toward warnings. 

Right now this is at the task configuration level, but we may need to do it at the task result reporting level instead... keep an eye on that (in case we need a task that could return either an error or a warning, depending on what it's inspecting. We could do that with an UPDATE_TASK action.
